config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :students, except: [:show]
  resources :courses, except: [:show]
  resources :classrooms, except: [:show, :edit, :update]
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true,
    uniqueness: { scope: :course, message: 'já está inscrito nesse curso' },
    inclusion: { in: StudentStatus.values_for(%w(ACTIVE)), message: "está inativo" }
  validates :course_id, presence: true,
    inclusion: { in: CourseStatus.values_for(%w(WAIT OPEN)), message: "está fechado" }
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms, dependent: :restrict_with_exception
  has_many :users, through: :classrooms

  has_enumeration_for :status, with: CourseStatus, create_helpers: { prefix: true }

  validates :name, length: { minimum: 2 , maximum: 45 }
  validates :status, inclusion: { in: CourseStatus.list }
  validates :description, length: { minimum: 2 , maximum: 45 }, allow_blank: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms, dependent: :restrict_with_exception
  has_many :users, through: :classrooms

  has_enumeration_for :status, with: StudentStatus, create_helpers: { prefix: true }

  validates :name, length: { minimum: 2 , maximum: 45 }
  validates :register_number, length: { minimum: 2 , maximum: 45 }, uniqueness: true
  validates :status, presence: true, inclusion: { in: StudentStatus.list }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_form_dependencies, only: [ :new, :create, :edit, :update ]
  before_action :set_classroom, only: [ :edit, :update, :show, :destroy ]

  def index
    @classrooms = Classroom.all.decorate
  end

  def new
    @classroom = Classroom.new
  end

  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      redirect_to classrooms_path, flash: { success: 'Matricula salva com sucesso' }
    else
      render :new
    end
  end

  def destroy
    @classroom.destroy
    redirect_to classrooms_path, flash: { success: 'Matricula cancelada com sucesso' }
  end

  private

    def set_form_dependencies
      @students = Student.where.not(status: StudentStatus::INACTIVE)
      @courses = Course.where.not(status: CourseStatus::CLOSED)
    end

    def set_classroom
      @classroom = Classroom.find_by_id(params[:id])
      redirect_to classrooms_path unless @classroom
    end

    def classroom_params
      params.require(:classroom).permit(:student_id, :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [ :edit, :update, :show, :destroy ]

  def index
    @courses = Course.all.decorate
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to courses_path, flash: { success: 'Curso cadastrado com sucesso' }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path, flash: { success: 'Curso alterado com sucesso' }
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_path, flash: { success: 'Curso apgado com sucesso' }
  rescue
    redirect_to students_path, flash: { error: 'Curso não pode ser apagado, porque tem em um ou mais alunos matriculados' }
  end

  private

    def set_course
      @course = Course.find_by_id(params[:id])
      redirect_to courses_path unless @course
    end

    def course_params
      params.require(:course).permit(:name, :status, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @courses = Course.limit(5).order(created_at: :desc).decorate
    @classrooms = Classroom.limit(5).order(created_at: :desc).decorate
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [ :edit, :update, :show, :destroy ]

  def index
    @students = Student.all.decorate
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to students_path, flash: { success: 'Aluno cadastrado com sucesso' }
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      redirect_to students_path, flash: { success: 'Aluno alterado com sucesso' }
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_path, flash: { success: 'Aluno apagado com sucesso' }
  rescue
    redirect_to students_path, flash: { error: 'Aluno não pode ser apagado, porque está matriculado em um ou mais cursos' }
  end

  private

    def set_student
      @student = Student.find_by_id(params[:id])
      redirect_to students_path unless @student
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def not_found_message model_name, gender = 'male'
    t("app.not_found.#{gender}", model_name: tm(model_name)).capitalize
  end

  def success_message model_name
    t("app.success", model_name: tm(model_name)).capitalize
  end
end

app/helpers/bootstrap_helper.rb
module BootstrapHelper
  def flash_message
    output = ''
    [:success, :info, :warning, :error, :notice, :alert].each do |type|
      if flash[type]
        class_name = type
        class_name = :danger if type == :error
        class_name = :info if type == :alert || type == :notice

        output += bs_alert(class_name, flash[type], type)
      end
    end

    output.html_safe
  end

  def bs_modal_confirm_destroy id, url, title='Atenção!', message='Você deseja realmente remover?'
    render 'shared/bootstrap/modal_confirm_destroy', id: id, url: url, title: title, message: message
  end

  def bs_alert type, message, subtitle=nil
    render 'shared/bootstrap/alert', type: type, message: message, subtitle: subtitle
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/font_awesome_helper.rb
module FontAwesomeHelper
  def fa_icon icon, options={}
    options[:class] = options[:class].present? ? "fa fa-fw fa-#{icon} #{options[:class]}" : "fa fa-fw fa-#{icon}"
    content_tag :i, nil, options
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_classrooms.html.erb
<table class="table no-margin">
  <thead>
    <tr>
      <th><%= ta Classroom, :student_id %> <small>(<%= ta Classroom, :course_id %>)</small></th>
      <th width="200" class="text-center"><%= ta Classroom, :created_at %></th>
      <th width="100" class="text-right">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td>
          <h5>
            <div><%= classroom.student_name %></div>
            <small><%= classroom.course_name %></small>
          </h5>
        </td>
        <td class="text-center">
          <h5>
            <span class="bs-tooltip" title="<%= classroom.created_datetime %>">
              <%= classroom.created_date %>
            </span>
          </h5>
        </td>
        <td>
          <div class="text-right">
            <span class="text-danger bs-tooltip" data-title="cancelar" data-toggle="modal" data-target="#classroom_destroy_<%= classroom.id %>">
              <%= fa_icon :ban %>
            </span>
          </div>

          <%= bs_modal_confirm_destroy "classroom_destroy_#{classroom.id}", classroom_path(classroom) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/classrooms/_form.html.erb
<%= form_for @classroom do |f| %>
<%= render 'shared/form_errors_messages', resource: @classroom %>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :student_id %>
      <%= f.collection_select :student_id, @students, :id, :name, { include_blank: true }, class: 'chosen' %>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :course_id %>
      <%= f.collection_select :course_id, @courses, :id, :name, { include_blank: true }, class: 'chosen' %>
    </div>
  </div>
</div>

<button type="submit" class="btn btn-sm btn-block btn-primary">
  <%= fa_icon :save %> Salvar <%= tm Classroom %>
</button>
<% end %>

app/views/classrooms/index.html.erb
<h3 class="page-header"><%= tmp Classroom %></h3>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-10 col-sm-8">
            <h4 class="no-margin">
              <%= fa_icon :list %> todas
            </h4>
          </div>
          <div class="col-xs-2 col-sm-4 text-right">
            <%= link_to new_classroom_path, class: 'btn btn-xs btn-primary', title: :adicionar do %>
              <%= fa_icon :plus %> <span class="hidden-xs">adicionar</span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <% if @classrooms.present? %>
          <%= render 'classrooms' %>
        <% else %>
          <%= not_found_message Classroom, :female %>, <%= link_to 'clique aqui para adicionar', new_classroom_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/classrooms/new.html.erb
<h3 class="page-header"><%= tmp Classroom %></h3>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-7">
            <h4 class="no-margin">
              <%= fa_icon :plus, class: 'text-muted' %> adicionar
            </h4>
          </div>
          <div class="col-xs-5 text-right">
            <%= link_to classrooms_path, class: 'btn btn-xs btn-default' do %>
              <%= fa_icon :'arrow-left' %> voltar
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/courses/_courses.html.erb
<table class="table no-margin">
  <thead>
    <tr>
      <th><%= ta Course, :name %> <small>(<%= ta Course, :description %>)</small></th>
      <th width="200"><%= ta Course, :status %></th>
      <th width="100" class="text-right">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td>
          <h5>
            <div><%= course.name %></div>
            <small><%= course.description %></small>
          </h5>
        </td>
        <td>
          <h5>
            <div><%= course.status_label %></div>
          </h5>
        </td>
        <td>
          <div class="text-right">
            <%= link_to edit_course_path(course), class: 'text-info bs-tooltip', title: :editar do %>
              <%= fa_icon 'pencil' %>
            <% end %>
            <span class="text-danger bs-tooltip" data-title="apagar" data-toggle="modal" data-target="#course_destroy_<%= course.id %>">
              <%= fa_icon 'times' %>
            </span>
          </div>

          <%= bs_modal_confirm_destroy "course_destroy_#{course.id}", course_path(course) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
<%= render 'shared/form_errors_messages', resource: @course %>

<div class="row">
  <div class="col-sm-8">
    <div class="form-group">
      <%= f.label :name, 'Nome*' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Nome do curso' %>
    </div>
  </div>

  <div class="col-sm-4">
    <div class="form-group">
      <%= f.label :status, 'Situação*' %>
      <%= f.select :status, CourseStatus.to_a, {}, class: 'chosen' %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="form-group">
      <%= f.label :description, 'Descrição' %>
      <%= f.text_field :description, class: 'form-control', placeholder: 'Descrição do curso' %>
    </div>
  </div>
</div>

<button type="submit" class="btn btn-sm btn-block btn-primary">
  <%= fa_icon :save %> Salvar <%= tm Course %>
</button>
<% end %>

app/views/courses/edit.html.erb
<h3 class="page-header"><%= tmp Course %></h3>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-7">
            <h4 class="no-margin">
              <%= fa_icon :pencil, class: 'text-muted' %> editar
            </h4>
          </div>
          <div class="col-xs-5 text-right">
            <%= link_to courses_path, class: 'btn btn-xs btn-default' do %>
              <%= fa_icon :'arrow-left' %> voltar
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<h3 class="page-header"><%= tmp Course %></h3>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-10 col-sm-8">
            <h4 class="no-margin">
              <%= fa_icon :list %> todos
            </h4>
          </div>
          <div class="col-xs-2 col-sm-4 text-right">
            <%= link_to new_course_path, class: 'btn btn-xs btn-primary', title: :adicionar do %>
              <%= fa_icon :plus %> <span class="hidden-xs">adicionar</span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <% if @courses.present? %>
          <%= render 'courses/courses' %>
        <% else %>
          <%= not_found_message Course %>, <%= link_to 'clique aqui para adicionar', new_course_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/new.html.erb
<h3 class="page-header"><%= tmp Course %></h3>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-7">
            <h4 class="no-margin">
              <%= fa_icon :plus, class: 'text-muted' %> adicionar
            </h4>
          </div>
          <div class="col-xs-5 text-right">
            <%= link_to courses_path, class: 'btn btn-xs btn-default' do %>
              <%= fa_icon :'arrow-left' %> voltar
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1 class="page-header">Dashboard</h1>

<div class="row">
  <div class="col-md-6">
    <h2 class="sub-header">Últimas matrículas</h2>
    <div class="table-responsive">
      <%= render 'classrooms/classrooms' %>
    </div>
  </div>

  <div class="col-md-6">
    <h2 class="sub-header">Últimos cursos</h2>
    <div class="table-responsive">
      <%= render 'courses/courses' %>
    </div>
  </div>
</div>

app/views/layouts/_sidebar_menu.html.erb
<ul class="nav nav-sidebar">
  <li>
    <%= link_to root_path do %>
      <%= fa_icon :dashboard, class: 'text-muted' %> Dashboard
    <% end %>
  </li>
</ul>
<ul class="nav nav-sidebar">
  <li class="dropdown-header"><%= fa_icon :'user-plus' %> <%= tmp Classroom %></li>
  <li>
    <%= link_to new_classroom_path do %>
      <%= fa_icon :plus, class: 'text-muted' %> Adicionar
    <% end %>
  </li>
  <li>
    <%= link_to classrooms_path do %>
      <%= fa_icon :list, class: 'text-muted' %> Ver todas
    <% end %>
  </li>
</ul>
<ul class="nav nav-sidebar">
  <li class="dropdown-header"><%= fa_icon :users %> <%= tmp Student %></li>
  <li>
    <%= link_to new_student_path do %>
      <%= fa_icon :plus, class: 'text-muted' %> Adicionar
    <% end %>
  </li>
  <li>
    <%= link_to students_path do %>
      <%= fa_icon :list, class: 'text-muted' %> Ver todos
    <% end %>
  </li>
</ul>
<ul class="nav nav-sidebar">
  <li class="dropdown-header"><%= fa_icon :flag %> <%= tmp Course %></li>
  <li>
    <%= link_to new_course_path do %>
      <%= fa_icon :plus, class: 'text-muted' %> Adicionar
    <% end %>
  </li>
  <li>
    <%= link_to courses_path do %>
      <%= fa_icon :list, class: 'text-muted' %> Ver todos
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title><%= ENV['APP_NAME'] %></title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only"><%= ENV['APP_NAME'] %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to ENV['APP_NAME'], root_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row">
    <div id="navbar" class="col-sm-3 col-md-2 sidebar">
      <%= render 'layouts/sidebar_menu' %>
    </div>

    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= flash_message %>
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/shared/_form_errors_messages.html.erb
<% if resource.errors.present? %>
<div class="alert alert-danger fade in">
  <i class="close" data-dismiss="alert"><%= fa_icon 'times' %></i>
  <b>Ops! Ocorreu algum problema:</b>

  <% if resource.errors.any? %>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li> * <%= message %></li>
      <% end %>
    </ul>
  <% end %>
</div>
<% end %>

app/views/shared/bootstrap/_alert.html.erb
<div class="alert fade in alert-<%= type %>">
  <span class="close" data-dismiss="alert"><%= fa_icon 'times' %></span>
  <% if subtitle.present? %>
    <b><%= t("app.flash_message.#{subtitle}").capitalize %>!</b> <br />
  <% end %>
  <%= message %>
</div>

app/views/shared/bootstrap/_modal_confirm_destroy.html.erb
<div class="modal fade" id="<%= id %>" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <span class="close" data-dismiss="modal">
          <%= fa_icon :times %>
        </span>
        <h3 class="modal-title"><%= title %></h3>
      </div>

      <div class="modal-body"><%= message %></div>

      <div class="modal-footer">
        <span class="btn btn-sm btn-default" data-dismiss="modal">
          <%= fa_icon 'arrow-left' %> cancelar
        </span>

        <%= link_to url, class: 'btn btn-sm btn-danger', method: :delete do %>
          <%= fa_icon :'trash-o' %> apagar
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
<%= render 'shared/form_errors_messages', resource: @student %>

<div class="row">
  <div class="col-sm-12">
    <div class="form-group">
      <%= f.label :name, 'Nome*' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Nome do aluno' %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :register_number, 'Matricula*' %>
      <%= f.text_field :register_number, class: 'form-control', placeholder: 'Matricula do aluno' %>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :status, 'Situação*' %>
      <%= f.select :status, StudentStatus.to_a, {}, class: 'chosen' %>
    </div>
  </div>
</div>

<button type="submit" class="btn btn-sm btn-block btn-primary">
  <%= fa_icon :save %> Salvar <%= tm Student %>
</button>
<% end %>

app/views/students/edit.html.erb
<h3 class="page-header"><%= tmp Student %></h3>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-7">
            <h4 class="no-margin">
              <%= fa_icon :pencil, class: 'text-muted' %> editar
            </h4>
          </div>
          <div class="col-xs-5 text-right">
            <%= link_to students_path, class: 'btn btn-xs btn-default' do %>
              <%= fa_icon :'arrow-left' %> voltar
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/students/index.html.erb
<h3 class="page-header"><%= tmp Student %></h3>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-10 col-sm-8">
            <h4 class="no-margin">
              <%= fa_icon :list %> todos
            </h4>
          </div>
          <div class="col-xs-2 col-sm-4 text-right">
            <%= link_to new_student_path, class: 'btn btn-xs btn-primary', title: :adicionar do %>
              <%= fa_icon :plus %> <span class="hidden-xs">adicionar</span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <% if @students.present? %>
          <table class="table no-margin">
            <thead>
              <tr>
                <th><%= ta Student, :name %> <small>(<%= ta Student, :register_number %>)</small></th>
                <th width="200"><%= ta Student, :status %></th>
                <th width="100" class="text-right">Ações</th>
              </tr>
            </thead>
            <tbody>
              <% @students.each do |student| %>
                <tr>
                  <td>
                    <h5>
                      <div><%= student.name %></div>
                      <small><%= student.register_number %></small>
                    </h5>
                  </td>
                  <td>
                    <h5>
                      <div><%= student.status_label %></div>
                    </h5>
                  </td>
                  <td>
                    <div class="text-right">
                      <%= link_to edit_student_path(student), class: 'text-info bs-tooltip', title: :editar do %>
                        <%= fa_icon 'pencil' %>
                      <% end %>
                      <span class="text-danger bs-tooltip" data-title="apagar" data-toggle="modal" data-target="#student_destroy_<%= student.id %>">
                        <%= fa_icon 'times' %>
                      </span>
                    </div>

                    <%= bs_modal_confirm_destroy "student_destroy_#{student.id}", student_path(student) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <%= not_found_message @students %>, <%= link_to 'clique aqui para adicionar', new_student_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<h3 class="page-header"><%= tmp Student %></h3>
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-7">
            <h4 class="no-margin">
              <%= fa_icon :plus, class: 'text-muted' %> adicionar
            </h4>
          </div>
          <div class="col-xs-5 text-right">
            <%= link_to students_path, class: 'btn btn-xs btn-default' do %>
              <%= fa_icon :'arrow-left' %> voltar
            <% end %>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>